// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRGYbvKk2SIM0mVwitvbNUXatH3-_Lz7Q',
    appId: '1:209196809810:web:76fc1261673acbccc0a98b',
    messagingSenderId: '209196809810',
    projectId: 'pillionpal-25a60',
    authDomain: 'pillionpal-25a60.firebaseapp.com',
    storageBucket: 'pillionpal-25a60.firebasestorage.app',
    measurementId: 'G-MJ5LFB3SF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCABMb7JwE-AQprufUma2KdU-qMALKUfZA',
    appId: '1:209196809810:android:9ed3eb8d4af62715c0a98b',
    messagingSenderId: '209196809810',
    projectId: 'pillionpal-25a60',
    storageBucket: 'pillionpal-25a60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXNpVSpv0OGH6MhRiseq3ToYPkcKGCQ9A',
    appId: '1:209196809810:ios:a9b3b350cfa10981c0a98b',
    messagingSenderId: '209196809810',
    projectId: 'pillionpal-25a60',
    storageBucket: 'pillionpal-25a60.firebasestorage.app',
    iosClientId: '209196809810-d5frai4ogo5bnarfs9mlhmuo2igof98q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXNpVSpv0OGH6MhRiseq3ToYPkcKGCQ9A',
    appId: '1:209196809810:ios:a9b3b350cfa10981c0a98b',
    messagingSenderId: '209196809810',
    projectId: 'pillionpal-25a60',
    storageBucket: 'pillionpal-25a60.firebasestorage.app',
    iosClientId: '209196809810-d5frai4ogo5bnarfs9mlhmuo2igof98q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRGYbvKk2SIM0mVwitvbNUXatH3-_Lz7Q',
    appId: '1:209196809810:web:72af73fe6c56b493c0a98b',
    messagingSenderId: '209196809810',
    projectId: 'pillionpal-25a60',
    authDomain: 'pillionpal-25a60.firebaseapp.com',
    storageBucket: 'pillionpal-25a60.firebasestorage.app',
    measurementId: 'G-7K479L1548',
  );

}